# Autogenerated by devscripts/update-version.py

__version__ = '2025.08.04.165237'

RELEASE_GIT_HEAD = 'd41b1470b4df3a481ca656ad91fd314dbe861d1b'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'hmarchen/yt-dlp'

ORIGIN = 'hmarchen/yt-dlp'

_pkg_version = '2025.08.04.165237'
