# Autogenerated by devscripts/update-version.py

__version__ = '2025.08.08.002411'

RELEASE_GIT_HEAD = 'cffa8bfa2f8d250d0d7c67d78bdfd6f176464c60'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'hmarchen/yt-dlp'

ORIGIN = 'hmarchen/yt-dlp'

_pkg_version = '2025.08.08.002411'
