# Autogenerated by devscripts/update-version.py

__version__ = '2025.08.01.015402'

RELEASE_GIT_HEAD = '926fcf7d84ea8310a33850fb8917f4868017936b'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'hmarchen/yt-dlp@++++++++++'

ORIGIN = 'hmarchen/yt-dlp'

_pkg_version = '2025.08.01.015402'
